### ISSUE TITLE
explanation

### ISSUE THREAD

**Issue by djeanner** [NMReDATAInitiative/javatools#1]
This repository needs a lot of documentation. How to install should be explicit in the main README.md file, reference to examples, demo also. Then in the demo/examples folder explain what can be done and is being done with the examples. This will show the interested user what he can do.

**Comment by stefhk3** [comment]
I have added a wiki. I have changed the readme a bit to avoid duplicate information, the readme has the main points, details are in the wiki. the demo/examples have various readmes, every help there welcome.
