### ISSUE TITLE
Update to JDK>8

### ISSUE THREAD

**Issue by bjonnh** [NMReDATAInitiative/javatools#4]
For example Double is now deprecated and unboxed in JDK>=9.

JDK8 is past its end of life.

**Comment by stefhk3** [comment]
which version would you recommend to use currently? I have jdk 11 installed, would that be good?

**Comment by bjonnh** [comment]
I think we need to stay with the LTS versions to not have to port it every 6 months. JDK11 is good until August 2024 so that should be fine.

**Comment by stefhk3** [comment]
Updated everything including the doc to use java 11.
