### ISSUE TITLE
Eror using "mvn install"

### ISSUE THREAD

**Issue by djeanner** [NMReDATAInitiative/javatools#6]
I get this error when I 
type "mvn install" from "src":
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for de.unikoeln.chemie.nmr:app:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.openscience.cdk:cdk-renderextra:jar should not point at files within the project directory, ${project.basedir}/cdk-renderextra.jar will be unresolvable by dependent projects @ line 62, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< de.unikoeln.chemie.nmr:app >---------------------
[INFO] Building app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for de.unikoeln.chemie.nmr:lib:jar:1.0-SNAPSHOT is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.1/commons-io-1.3.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.1/commons-io-1.3.1.jar (84 kB at 76 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.621 s
[INFO] Finished at: 2020-05-22T06:29:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project app: Could not resolve dependencies for project de.unikoeln.chemie.nmr:app:jar:1.0-SNAPSHOT: Could not find artifact de.unikoeln.chemie.nmr:lib:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by djeanner** [comment]
Similar error from "app":
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for de.unikoeln.chemie.nmr:app:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.openscience.cdk:cdk-renderextra:jar should not point at files within the project directory, ${project.basedir}/cdk-renderextra.jar will be unresolvable by dependent projects @ line 62, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< de.unikoeln.chemie.nmr:app >---------------------
[INFO] Building app 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for de.unikoeln.chemie.nmr:lib:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.241 s
[INFO] Finished at: 2020-05-22T06:31:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project app: Could not resolve dependencies for project de.unikoeln.chemie.nmr:app:jar:1.0-SNAPSHOT: Could not find artifact de.unikoeln.chemie.nmr:lib:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by stefhk3** [comment]
you need to build lib first (I think there should be a parent pom for both, but I haven't done that yet). So go to lib, do mvn install, then in app (not src) do mvn install, and it should work. Notice your build of app says lib is missing, which is why lib needs to be built first. Or should maven pick that up? I don't think so.

**Comment by stefhk3** [comment]
I added a pom.xml to the root project. doing an mvn install there, should build the subprojects as required. Please see if this works.
